# Generated by Django 5.1.3 on 2024-12-13 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Global', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects',
            name='classes',
            field=models.ManyToManyField(to='Global.subclasses', verbose_name='Classes'),
        ),
    ]
