# Generated by Django 5.1.3 on 2024-12-11 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Global', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approvals',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='approvals',
            name='lastname',
        ),
        migrations.AddField(
            model_name='approvals',
            name='fullname',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='fullname'),
        ),
    ]
