# Generated by Django 5.1.3 on 2024-12-13 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Global', '0003_alter_staff_teacher_class'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Assessments',
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_id',
        ),
    ]
