# Generated by Django 5.1.3 on 2024-12-11 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_schoolprofile_initial_update_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='approved'),
        ),
    ]
